<?php

namespace Database\Seeders;

use App\Models\Textbook;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TextBooksTableSeedr extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (Textbook::count()) {
            Textbook::truncate();
        }

        $Textbooks = [
            ['name' => 'همه', 'grade_id'=>1 ,'field_id' => 1],
            ['name' => 'فارسی (1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'دین و زندگی(1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'زبان انگلیسی (1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'نگارش (1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'جغرافیای ایران', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'ریاضی (1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'فیزیک (1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'شیمی (1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'هندسه (1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'عربی (1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'آزمایشگاه علوم تجربی (1)', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'آمادگی دفاعی', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'تفکر و سواد رسانه‌ای', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'کارگاه کار آفرینی و تولید', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'هنر', 'grade_id'=>11 ,'field_id' => 2],
            ['name' => 'جامع دروس ریاضی', 'grade_id'=>11 ,'field_id' => 2],
            //دهم تجربی
            ['name' => 'فارسی (1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'دین و زندگی(1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'زبان انگلیسی (1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'نگارش (1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'جغرافیای ایران', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'ریاضی (1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'فیزیک (1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'شیمی (1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'زیست شناسی (1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'عربی (1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'آزمایشگاه علوم تجربی (1)', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'آمادگی دفاعی', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'تفکر و سواد رسانه‌ای', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'کارگاه کار آفرینی و تولید', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'هنر', 'grade_id'=>11 ,'field_id' =>3],
            ['name' => 'جامع دروس تجربی', 'grade_id'=>11 ,'field_id' =>3],
            //دهم علوم انسانی
            ['name' => 'فارسی (1)', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'دین و زندگی(1)', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'زبان انگلیسی (1)', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'نگارش (1)', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'جغرافیای ایران', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'عربی (1)', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'علوم و فنون ادبی (1)', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'اقتصاد', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'جامعه شناسی (1)', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'منطق', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'تاریخ (1)', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'ریاضی و آمار (1)', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'آمادگی دفاعی', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'تفکر و سواد رسانه‌ای', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'کارگاه کار آفرینی و تولید', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'هنر', 'grade_id'=>11 ,'field_id' =>4],
            ['name' => 'جامع دروس انسانی', 'grade_id'=>11 ,'field_id' =>4],
            //دهم علوم و معارف اسلامی
            ['name' => 'فارسی (1)', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'زبان انگلیسی (1)', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'نگارش (1)', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'جغرافیای ایران', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'اصول عقاید (1)', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'علوم و معارف قرآنی (1)', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'احکام و استنباط (1)', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'منطق', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'اخلاق (1)', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'عربی (1)', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'تاریخ اسلام (1)', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'آمادگی دفاعی', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'تفکر و سواد رسانه‌ای', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'کارگاه کار آفرینی و تولید', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'هنر', 'grade_id'=>11 ,'field_id' =>5],
            ['name' => 'جامع دروس معارف', 'grade_id'=>11 ,'field_id' =>5],
            //یازدهم ریاضی

            ['name' => 'دین و زندگی(2)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'فارسی (2)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'نگارش (2)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'زبان انگلیسی (2)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'عربی (2)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'حسابان (1)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'شیمی (2)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'فیزیک (2)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'زمین شناسی', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'هندسه (2)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'آمار و احتمال', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'آزمایشگاه علوم تجربی (2)', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'تاریخ معاصر ایران', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'انسان و محیط زیست', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'تفکر و سواد رسانه‌ای', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'کارگاه کار آفرینی و تولید', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'هنر', 'grade_id'=>12 ,'field_id' =>2],
            ['name' => 'جامع دروس ریاضی', 'grade_id'=>12 ,'field_id' =>2],
            //یازدهم تجربی
            ['name' => 'دین و زندگی(2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'فارسی (2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'نگارش (2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'زبان انگلیسی (2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'عربی (2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'فیزیک (2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'ریاضی (2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'شیمی (2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'زیست شناسی (2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'زمین شناسی', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'آزمایشگاه علوم تجربی (2)', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'تاریخ معاصر ایران', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'انسان و محیط زیست', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'تفکر و سواد رسانه‌ای', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'کارگاه کار آفرینی و تولید', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'هنر', 'grade_id'=>12 ,'field_id' =>3],
            ['name' => 'جامع دروس تجربی', 'grade_id'=>12 ,'field_id' =>3],
            //یازدهم انسانی
            ['name' => 'دین و زندگی (2)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'فارسی (2)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'نگارش (2)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'زبان انگلیسی (2)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'روانشناسی', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'عربی (2) انسانی', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'علوم و فنون ادبی (2)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'ریاضی و آمار (2)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'جامعه شناسی (2)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'جغرافیا (2)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'فلسفه (1)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'تاریخ (2)', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'انسان و محیط زیست', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'تفکر و سواد رسانه‌ای', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'کارگاه کار آفرینی و تولید', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'هنر', 'grade_id'=>12 ,'field_id' =>4],
            ['name' => 'جامع دروس انسانی', 'grade_id'=>12 ,'field_id' =>4],
            //یازدهم علوم و معارف اسلامی
            ['name' => 'دین و زندگی (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'فارسی (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'نگارش (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'زبان انگلیسی (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'علوم و معارف قرآنی (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'اصول عقاید (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'اقتصاد', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'احکام (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'اخلاق (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'تاریخ (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'عربی (2)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'فلسفه (1)', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'مطالعات فرهنگی', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'انسان و محیط زیست', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'تفکر و سواد رسانه‌ای', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'کارگاه کار آفرینی و تولید', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'هنر', 'grade_id'=>12 ,'field_id' =>5],
            ['name' => 'جامع دروس معارف', 'grade_id'=>12 ,'field_id' =>5],
            //داوزدهم ریاضی
            ['name' => 'فارسی (3)', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'نگارش (3)', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'زبان انگلیسی (3)', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'دین و زندگی(3)', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'شیمی (3)', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'عربی (3)', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'فیزیک (3) ریاضی', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'هندسه (3)', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'حسابان (2)', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'ریاضیات گسسته', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'هویت اجتماعی', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'سلامت و بهداشت', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'مدیریت خانواده و سبک زندگی دختران', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'مدیریت خانواده و سبک زندگی پسران', 'grade_id'=>13 ,'field_id' =>2],
            ['name' => 'جامع دروس ریاضی', 'grade_id'=>13 ,'field_id' =>2],

            //دوزادهم تجربی
            ['name' => 'فارسی (3)', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'نگارش (3)', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'زبان انگلیسی (3)', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'دین و زندگی(3)', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'شیمی (3)', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'عربی (3)', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'فیزیک (3) تجربی', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'ریاضی (3)', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'زیست شناسی (3)', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'هویت اجتماعی', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'سلامت و بهداشت', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'مدیریت خانواده و سبک زندگی دختران', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'مدیریت خانواده و سبک زندگی پسران', 'grade_id'=>13 ,'field_id' =>3],
            ['name' => 'جامع دروس تجربی', 'grade_id'=>13 ,'field_id' =>3],

            //دوازدهم انسانی
            ['name' => 'فارسی (3)', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'نگارش (3)', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'زبان انگلیسی (3)', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'دین و زندگی (3) انسانی', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'عربی (3) انسانی', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'علوم و فنون ادبی (3)', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'ریاضی و آمار (3)', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'جغرافیا (3)', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'تاریخ (3)', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'جامعه شناسی (3)', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'فلسفه (2)', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'مطالعات فرهنگی', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'سلامت و بهداشت', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'مدیریت خانواده و سبک زندگی دختران', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'مدیریت خانواده و سبک زندگی پسران', 'grade_id'=>13 ,'field_id' =>4],
            ['name' => 'جامع دروس انسانی', 'grade_id'=>13 ,'field_id' =>4],
            //دوازدهم علوم و معارف اسلامی
            ['name' => 'فارسی (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'نگارش (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'زبان انگلیسی (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'عربی (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'تاریخ (3) معارف', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'اصول عقاید (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'احکام (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'علوم و فنون ادبی (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'اخلاق (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'ریاضی و آمار (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'علوم و معارف قرآنی (3)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'جریان شناسی اندیشه‌های معاصر', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'فلسفه (2)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'سلامت و بهداشت', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'مدیریت خانواده و سبک زندگی دختران', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'مدیریت خانواده و سبک زندگی (پسران 1)', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'مدیریت خانواده و سبک زندگی پسران ', 'grade_id'=>13 ,'field_id' =>5],
            ['name' => 'جامع دروس معارف', 'grade_id'=>13 ,'field_id' =>5],


        ];

        foreach ($Textbooks as $Textbook) {
            Textbook::create($Textbook);
        }
    }
}

